### ISSUE TITLE
Add contributing file

### ISSUE THREAD

**Issue by laysauchoa** [aiven/opensearch-migration-examples#11]
**What are the changes?**
Hey 🙋🏻‍♀️, do you think is a good idea to add a contributing file with the steps in how to get started contributing to this repository?

I am adding here the recommendations from @davidespo 
- First commit should be a full ES example duplicated in `es-main.py` and `main.py`
- Second commit should be full OS example in `os-main.py` and then modify `main.py` to use the OS client with minimal changes

**Where would you expect to find this information?**
It should have it's own file and be linked to the readme of the repository

**Comment by jlprat** [comment]
Hi @laysauchoa yes!
We would love for all Open Source projects to have at least:
- "Getting Started" guide -- how can I run this project
- Contributing documentation -- what do I need to provide? any technical considerations? how do I build the project?

**Comment by laysauchoa** [comment]
This I am a bit confused because I understand that every example here should have it is own `README.md` file that contains the `Getting Started` on it.

1) If you add a new project, you should add those guidelines in your `README.md` file.
2) If you are running one of the examples, those guidelines are expressed in the `README.md` of the example
3) If you are adding an example, then you should follow those commits guidelines suggested by @davidespo as well you need to add a `README.md` file with the commit changes and how to run.

I am adding more about the 3) here. As the other ones, should be added when an example is added. 

I am not sure if you meant to bring those README.md to the CONTRIBUTING.rst or maybe we can link them. What is your suggestion, @jlprat?

**Comment by jlprat** [comment]
My comment was more of a general comment than an specific one for this project.

As long as the contributing information is present in the repository, and it's easily accessible, I'm happy with the whichever way we choose :)
