### ISSUE TITLE
Add CI that runs tests on PRs and when merging on the main branch.

### ISSUE THREAD

**Issue by jlprat** [aiven/opensearch-migration-examples#3]
In order to minimize the risk of having broken builds, we should add a GitHub Action that runs on every PR so we can make sure changes done are not breaking the build.
Additionally, having a run on CI after merging would guarantee that the "trunk" is always "buildable".

The command for the GitHub Action for the moment would suffice being:

```bash
./gradlew clean build
```

Please note, that the java project is in a sub-folder.

**Comment by mohitsaxenaknoldus** [comment]
I can do this if you tell me how your project is built or what you want the CI to run. (I couldn't any `Getting Started` in the repo).
And, any preferred CI tool?

**Comment by jlprat** [comment]
Hi @mohitsaxenaknoldus sorry for the delay. I will update the original description of the ticket, but we would like to use GitHub Actions. And in regards to what should be run, I think `./gradlew clean build` for the Java example would suffice.

**Comment by jlprat** [comment]
You can find a similar example here: https://github.com/aiven/gcs-connector-for-apache-kafka/blob/master/.github/workflows/pull_request_workflow.yml

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by jlprat** [comment]
Thanks for working on this!

**Comment by mohitsaxenaknoldus** [comment]
@jlprat PR: https://github.com/aiven/opensearch-migration-examples/pull/4
