### ISSUE TITLE
Duplicate code in main.js and os-client-main.js

### ISSUE THREAD

**Issue by laysauchoa** [aiven/opensearch-migration-examples#7]
Can you help me to understand why there are two files with the same content? It was not clear for me. 

`❯ diff -w main.js os-client-main.js`

- [main.js](https://github.com/aiven/opensearch-migration-examples/blob/main/node-client-migration/src/main.js)
- [os-client-main.js](https://github.com/aiven/opensearch-migration-examples/blob/main/node-client-migration/src/os-client-main.js)

**Comment by davidespo** [comment]
Yes, I provided three files:

* `es-client-main.js`: This is a full working example for using ES client libraries to target ES/OS clusters
* `os-client-main.js`: This is a full working example for using OS client libraries to target ES/OS clusters
* `main.js`: This file is meant to show the changes require for switching between the two client libraries as can be seen in its commit history.
